[tabs]
bar = { bg = "#222222", fg = "#cccccc" }
active = { bg = "#cccccc", fg = "#222222" }
inactive = { bg = "#444444", fg = "#dddddd" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[indicator]
padding = { open = "█", close = "█" }

[status]
sep_left = { open = " ", close = "" }
sep_right = { open = "", close = " " }
overall = { fg = "#ffffff", bg = "#222222" }
