font pango:JetBrainsMono Nerd Font Italic Bold 13.0
exec_always --no-startup-id feh --bg-fill $WALLPAPER

# Move focused window.
bindsym $super+$altr+Left  move left
bindsym $super+$altr+Down  move down
bindsym $super+$altr+Up    move up
bindsym $super+$altr+Right move right

# Move focused container to a workspace.
bindsym $super+Control+$altr+Left   move container to workspace "$wsh"; workspace "$wsh"
bindsym $super+Control+$altr+Down   move container to workspace "$wsj"; workspace "$wsj"
bindsym $super+Control+$altr+Up     move container to workspace "$wsk"; workspace "$wsk"
bindsym $super+Control+$altr+Right  move container to workspace "$wsl"; workspace "$wsl"
bindsym $super+Control+$altr+U1F642 move container to workspace "$wss"; workspace "$wss"
bindsym $super+Control+$altr+U201E  move container to workspace "$wsa"; workspace "$wsa"

# Toggle backlight between low and high.
bindsym $super+F6 exec --no-startup-id polybar-msg action "#backlight.hook.1"
bindsym $super+F5 exec --no-startup-id polybar-msg action "#nightshift.hook.1"
