presets = "proc:0:default,cpu:1:default"
update_ms = 150
save_config_on_exit = false

cpu_graph_upper = "total"
cpu_graph_lower = "gpu-totals"
show_gpu_info = "On"
rounded_corners = false
proc_gradient = false

